export const SET_PRODUCTS = "SET_PRODUCTS";
export const SET_CATEGORIES = "SET_CATEGORIES";
export const LOAD_CURRENT_PRODUCT = "LOAD_CURRENT_PRODUCT";
export const REMOVE_CURRENT_PRODUCT = "REMOVE_CURRENT_PRODUCT";
