export const SET_PRODUCTS = "SET_PRODUCTS";
export const SET_CATEGORIES = "SET_CATEGORIES";
export const SET_ORDERS = "SET_ORDERS";
export const SHOW_LOADING = "SHOW_LOADING";
export const LOAD_CURRENT_PRODUCT = "LOAD_CURRENT_PRODUCT";
export const REMOVE_CURRENT_PRODUCT = "REMOVE_CURRENT_PRODUCT";
export const SHOW_MESSAGE = "SHOW_MESSAGE";
export const SHOW_MODAL_PRODUCT = "SHOW_MODAL_PRODUCT";
